"issue": "Issue"
# organization
"issue.issue-type": "Issue Type"
"issue.issue-type-schemes": "Issue Type Schemes"
"issue.state-machine-schemes": "StateMachine Schemes"
"issue.issue-type-screen-schemes": "Issue Type Screen Schemes"
"issue.priorities": "Priorities"
"issue.state": "State"
"issue.state-machine": "StateMachine"
